#ifndef MYERROR_HPP
#define MYERROR_HPP

#include <string>

typedef enum {
    MISS_SEMI,
    MISS_RC,
    MISS_RP,
    MISS_SPEC,
    MISS_RB,
    UNDEFINED_VARIABLE,
    UNDEFINED_FUNC,
    REDEFINED_VARIABLE,
    REDEFINED_FUNC,
    ASSIGN_UNMATCH,
    RVALUE_ERROR,
    UNMATCH_OPERAND,
    RETURN_VALUE_MISMATCH,
    ARGS_MISMATCH,
    INDEX_OPERATOR_ERROR,
    FUNC_INVOKE_ERROR,
    INDEX_TYPE_ERROR,
    DOT_ERROR,
    UNDEFINED_STRUCT_MEMBER,
    REDEFINED_STRUCT,
    STRUCT_MISMATCH 
} MY_ERROR_TYPE;

void my_error(MY_ERROR_TYPE type, int line_num);

void my_error(MY_ERROR_TYPE type, int line_num, const char* name);

#endif 
