echo In test1
diff myOutput/output1.txt student_test/test_1_s01.out
echo In test2
diff myOutput/output2.txt student_test/test_1_s02.out
echo In test3
diff myOutput/output3.txt student_test/test_1_s03.out
echo In test4
diff myOutput/output4.txt student_test/test_1_s04.out
echo In test5
diff myOutput/output5.txt student_test/test_1_s05.out
echo In test6
diff myOutput/output6.txt student_test/test_1_s06.out
echo In test7
diff myOutput/output7.txt student_test/test_1_s07.out
echo In test8
diff myOutput/output8.txt student_test/test_1_s08.out
echo In test9
diff myOutput/output9.txt student_test/test_1_s09.out
echo In test10
diff myOutput/output10.txt student_test/test_1_s10.out
echo In test11
diff myOutput/output11.txt student_test/test_1_s11.out
echo In test12
diff myOutput/output12.txt student_test/test_1_s12.out
echo In test13
diff myOutput/output13.txt student_test/test_1_s13.out
echo In test14
diff myOutput/output14.txt student_test/test_1_s14.out
echo In test15
diff myOutput/output15.txt student_test/test_1_s15.out
echo In test16
diff myOutput/output16.txt student_test/test_1_s16.out

