./bin/splc student_test/test_1_s01.spl > myOutput/output1.txt
./bin/splc student_test/test_1_s02.spl > myOutput/output2.txt
./bin/splc student_test/test_1_s03.spl > myOutput/output3.txt
./bin/splc student_test/test_1_s04.spl > myOutput/output4.txt
./bin/splc student_test/test_1_s05.spl > myOutput/output5.txt
./bin/splc student_test/test_1_s06.spl > myOutput/output6.txt
./bin/splc student_test/test_1_s07.spl > myOutput/output7.txt
./bin/splc student_test/test_1_s08.spl > myOutput/output8.txt
./bin/splc student_test/test_1_s09.spl > myOutput/output9.txt
./bin/splc student_test/test_1_s10.spl > myOutput/output10.txt
./bin/splc student_test/test_1_s11.spl > myOutput/output11.txt
./bin/splc student_test/test_1_s12.spl > myOutput/output12.txt
./bin/splc student_test/test_1_s13.spl > myOutput/output13.txt
./bin/splc student_test/test_1_s14.spl > myOutput/output14.txt
./bin/splc student_test/test_1_s15.spl > myOutput/output15.txt
./bin/splc student_test/test_1_s16.spl > myOutput/output16.txt