./bin/splc github_test/test_1_r01.spl > myOutput/output1.txt
./bin/splc github_test/test_1_r02.spl > myOutput/output2.txt
./bin/splc github_test/test_1_r03.spl > myOutput/output3.txt
./bin/splc github_test/test_1_r04.spl > myOutput/output4.txt
./bin/splc github_test/test_1_r05.spl > myOutput/output5.txt
./bin/splc github_test/test_1_r06.spl > myOutput/output6.txt
./bin/splc github_test/test_1_r07.spl > myOutput/output7.txt
./bin/splc github_test/test_1_r08.spl > myOutput/output8.txt
./bin/splc github_test/test_1_r09.spl > myOutput/output9.txt
./bin/splc github_test/test_1_r10.spl > myOutput/output10.txt
./bin/splc github_test/test_1_r11.spl > myOutput/output11.txt
./bin/splc github_test/test_1_r12.spl > myOutput/output12.txt
